<a href="https://colab.research.google.com/github/rkrzy/data_analysis/blob/main/homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#문제 1
#1부터 100까지(100 포함), 간격(step)이 1인 NumPy 배열을 만드세요.
#모든 짝수들의 합과 모든 홀수들의 합을 각각 구해서 출력하세요.

import numpy as np

arr = np.arange(1, 101)  # 1부터 100까지
even_sum = np.sum(arr[arr % 2 == 0])  # 짝수만 더해준다
odd_sum = np.sum(arr[arr % 2 == 1])   # 홀수만 더해준다

print("짝수 합:", even_sum)
print("홀수 합:", odd_sum)


[문제1]
짝수 합: 2550
홀수 합: 2500


In [13]:
# 문제 2 풀이
# 요구사항
# 행렬 A, B 구성

# A+B, A-B, A·B, A^T, B^T 수행

import numpy as np

A = np.array([[2, 4],
              [1, 3]])
B = np.array([[5, 2],
              [7, 1]])

print("A + B =\n", A + B)
print("A - B =\n", A - B)
print("A dot B =\n", np.dot(A, B))
print("A^T =\n", A.T)
print("B^T =\n", B.T)


[문제2]
A + B =
 [[7 6]
 [8 4]]
A - B =
 [[-3  2]
 [-6  2]]
A dot B =
 [[38  8]
 [26  5]]
A^T =
 [[2 1]
 [4 3]]
B^T =
 [[5 7]
 [2 1]]


In [14]:
# 문제 3 풀이
# 요구사항
# nba_salaries.csv 파일에서, 각 시즌마다 최고 연봉과 최저 연봉의 차이 구하기

import pandas as pd

df = pd.read_csv('nba_salaries.csv')

grouped = df.groupby('SEASON')['SALARY']


for season, group in grouped:
    max_salary = group.max()
    min_salary = group.min()
    diff = max_salary - min_salary
    print(f"Season {season}: {diff}")


Season 2000: 16841000
Season 2001: 19576000
Season 2002: 22163000
Season 2003: 24688000
Season 2004: 27413000
Season 2005: 28087000
Season 2006: 19751882
Season 2007: 20976557
Season 2008: 23747401
Season 2009: 24705017
Season 2010: 23031683
Season 2011: 24797892
Season 2012: 25233035
Season 2013: 30433702
Season 2014: 30445573
Season 2015: 23470517
Season 2016: 24969112
Season 2017: 30957683
Season 2018: 37452546
Season 2019: 37452417
Season 2020: 40076111


In [16]:
# 문제 4 풀이
# 요구사항
# SEASON, TEAM으로 그룹화
# 각 팀별 총연봉 합
# 각 시즌마다
# 가장 연봉 합이 높은 팀 (금액)
# 가장 연봉 합이 낮은 팀 (금액)

import pandas as pd

df = pd.read_csv('nba_salaries.csv')

grouped = df.groupby(['SEASON', 'TEAM'], as_index=False)['SALARY'].sum()


season_grouped = grouped.groupby('SEASON')

for season, sub_df in season_grouped:
    max_row = sub_df.loc[sub_df['SALARY'].idxmax()]  # SALARY 최댓값 행
    min_row = sub_df.loc[sub_df['SALARY'].idxmin()]  # SALARY 최솟값 행

    max_team, max_salary = max_row['TEAM'], max_row['SALARY']
    min_team, min_salary = min_row['TEAM'], min_row['SALARY']

    print(f"\nSeason {season}:")
    print(f"가장 높은 총 연봉: 팀={max_team}, 금액={max_salary}")
    print(f"가장 낮은 총 연봉: 팀={min_team}, 금액={min_salary}")



Season 2000:
가장 높은 총 연봉: 팀=Portland Trail Blazers, 금액=49423000
가장 낮은 총 연봉: 팀=Chicago Bulls, 금액=4454000

Season 2001:
가장 높은 총 연봉: 팀=Portland Trail Blazers, 금액=84918000
가장 낮은 총 연봉: 팀=Atlanta Hawks, 금액=19721000

Season 2002:
가장 높은 총 연봉: 팀=Portland Trail Blazers, 금액=83995000
가장 낮은 총 연봉: 팀=Chicago Bulls, 금액=24038000

Season 2003:
가장 높은 총 연봉: 팀=Portland Trail Blazers, 금액=77424000
가장 낮은 총 연봉: 팀=LA Clippers, 금액=25449000

Season 2004:
가장 높은 총 연봉: 팀=New York Knicks, 금액=107898000
가장 낮은 총 연봉: 팀=Boston Celtics, 금액=2104000

Season 2005:
가장 높은 총 연봉: 팀=New York Knicks, 금액=108616000
가장 낮은 총 연봉: 팀=New Orleans Hornets, 금액=5474000

Season 2006:
가장 높은 총 연봉: 팀=Orlando Magic, 금액=91980866
가장 낮은 총 연봉: 팀=Brooklyn Nets, 금액=4501200

Season 2007:
가장 높은 총 연봉: 팀=Indiana Pacers, 금액=81585398
가장 낮은 총 연봉: 팀=Oklahoma City Thunder, 금액=664209

Season 2008:
가장 높은 총 연봉: 팀=Phoenix Suns, 금액=91843875
가장 낮은 총 연봉: 팀=Madrid Real Madrid, 금액=1511243

Season 2009:
가장 높은 총 연봉: 팀=Boston Celtics, 금액=100827179
가장 낮은 총 연봉: 팀=null Unknown