<a href="https://colab.research.google.com/github/rkrzy/data_analysis/blob/main/W3L2_Python_Fast_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PNUCSE 데이터과학입문  
## 3주차 실습자료  
### 교강사: 박영진, youngjinpark@pusan.ac.kr
---

## 실습 목표

- Python Review
- Types
- Array


#Python Review

In [ ]:
# p.4
print(64 / 8)

In [ ]:
# p.5
hours_per_wk = 24 * 7
print(hours_per_wk)

168


In [ ]:
# p.8, 에러 발생 유도함.
abs(-1, 2)

In [ ]:
# p.8
a = abs(-10)
print(a)

In [ ]:
# p.8
a = round(number=12.74)
print(a)

13


In [ ]:
# p.8
abs?

#Types

In [ ]:
# p.10, float형 정밀도 확인을 위한 코드
a = 1.000005
b = 1.0000000000000005
c = 1.00000000000000005
print(a)
print(b)
print(c)

1.000005
1.0000000000000004
1.0


In [ ]:
# p.11
a = int('12')
b = float('1.2')
print(a + b)

13.2


In [ ]:
# p.11, 에러 발생 유도함.
a = str(5)
print(4 + a)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
# p.12, 에러 발생 유도함.
a = float('one point two')

In [ ]:
# p.12
a = int(1.2)
print(a)

1


In [ ]:
# p.13, 에러 발생 유도함.
x = 3
y = '4'
z = '5.6'

print(x + y)
print(x + int(y + z))
print(str(x) + int(y))
print(y + float(z))

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
# p.14
print(type(2))
print(type(2 + 2))
x = 2
print(type(x))

<class 'int'>
<class 'int'>
<class 'int'>


#Arrays

In [ ]:
# p.18
from datascience import *
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [ ]:
# p.18
import numpy as np
eps_arr = np.array(["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
eps_arr

arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([4,5,6])
print(arr2)
print(arr1 + arr2)

[1 2 3]
[4 5 6]
[5 7 9]


In [ ]:
# p.19
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684)
highs

In [ ]:
# p.19
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684])
highs

In [ ]:
# p.19
baseline_low = 3.00
lows = np.array([baseline_low - 0.872, baseline_low - 0.629, baseline_low - 0.126, baseline_low + 0.728])
lows

In [ ]:
# p.20
np.array([
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
])
highs - lows

NameError: name 'highs' is not defined

In [ ]:
# p.21
arr = np.array([0.0, 1.0, 2.0, 3.0])

a = np.prod(arr)
print(a)

b = np.sum(arr)
print(b)

c = np.all(arr)
print(c)

d = np.any(arr)
print(d)

e = np.count_nonzero(arr)
print(e)

In [ ]:
# p.23
a = np.arange(5)
print(a)

b = np.arange(3, 9)
print(b)

c = np.arange(start=3, stop=9)
print(c)

d = np.arange(1.5, -2, -0.5)
print(d)

e = np.arange(start=1.5, stop=-2, step=-0.5)
print(e)

In [ ]:
# p.25
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

In [ ]:
# p.25
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

In [ ]:
# p.25
positive_terms = 1 / positive_term_denominators
negative_terms = 1 / (positive_term_denominators + 2)

4 * (sum(positive_terms) - sum(negative_terms))

In [ ]:
# p.26
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)